LeaseManager/Models/VehicleAllocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LeaseManager.Models
{
    public class VehicleAllocation
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Vehicle")]
        public int VehicleId { get; set; }
        [Display(Name = "Branch")]
        public int BranchId { get; set; }
        [Display(Name = "Date From")]
        [DataType(DataType.Date)]
        public DateTime DateFrom { get; set; }
        [Display(Name = "Date To")]
        [DataType(DataType.Date)]
        public DateTime? DateTo { get; set; }
        public string Purpose { get; set; }

        public virtual Vehicle Vehicle { get; set; }
        public virtual Branch Branch { get; set; }
    }
}

LeaseManager/Controllers/VehicleAllocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeaseManager.Models;

namespace LeaseManager.Controllers
{
    public class VehicleAllocationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VehicleAllocations
        public ActionResult Index()
        {
            var vehicleAllocations = db.VehicleAllocations.Include(v => v.Branch).Include(v => v.Vehicle);
            return View(vehicleAllocations.ToList());
        }

        // GET: VehicleAllocations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleAllocation vehicleAllocation = db.VehicleAllocations.Find(id);
            if (vehicleAllocation == null)
            {
                return HttpNotFound();
            }
            return View(vehicleAllocation);
        }

        // GET: VehicleAllocations/Create
        public ActionResult Create()
        {
            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name");
            ViewBag.VehicleId = new SelectList(db.Vehicles, "Id", "Make");
            return View();
        }

        // POST: VehicleAllocations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,VehicleId,BranchId,DateFrom,DateTo,Purpose")] VehicleAllocation vehicleAllocation)
        {
            if (ModelState.IsValid)
            {
                db.VehicleAllocations.Add(vehicleAllocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name", vehicleAllocation.BranchId);
            ViewBag.VehicleId = new SelectList(db.Vehicles, "Id", "Make", vehicleAllocation.VehicleId);
            return View(vehicleAllocation);
        }

        // GET: VehicleAllocations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleAllocation vehicleAllocation = db.VehicleAllocations.Find(id);
            if (vehicleAllocation == null)
            {
                return HttpNotFound();
            }
            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name", vehicleAllocation.BranchId);
            ViewBag.VehicleId = new SelectList(db.Vehicles, "Id", "Make", vehicleAllocation.VehicleId);
            return View(vehicleAllocation);
        }

        // POST: VehicleAllocations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,VehicleId,BranchId,DateFrom,DateTo,Purpose")] VehicleAllocation vehicleAllocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleAllocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name", vehicleAllocation.BranchId);
            ViewBag.VehicleId = new SelectList(db.Vehicles, "Id", "Make", vehicleAllocation.VehicleId);
            return View(vehicleAllocation);
        }

        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleAllocation vehicleAllocation = db.VehicleAllocations.Find(id);
            db.VehicleAllocations.Remove(vehicleAllocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeaseManager/Views/VehicleAllocations/Create.cshtml
@model LeaseManager.Models.VehicleAllocation

@{
    ViewBag.Title = "Vehicle Allocation";
}

<h2 class="title text-center">@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <tr>
                    <th>@Html.LabelFor(model => model.DateFrom)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar-o"></i>
                            </div>
                            @Html.EditorFor(m => m.DateFrom, new { htmlAttributes = new { @type = "date", @class = "form-control", @required = "required", @placeholder = "Date From", min = DateTime.Now.ToString("yyyy-MM-dd") } })
                        </div>
                        @Html.ValidationMessageFor(m => m.DateFrom, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.DateTo)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar-o"></i>
                            </div>
                            @Html.EditorFor(m => m.DateTo, new { htmlAttributes = new { @type = "date", @class = "form-control", @required = "required", @placeholder = "Date To", min = DateTime.Now.ToString("yyyy-MM-dd") } })
                        </div>
                        @Html.ValidationMessageFor(m => m.DateTo, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>Vehicle</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </div>
                            @Html.DropDownList("VehicleId", null, "--- Please Select ---", new { @class = "form-control", @required = "required" })
                        </div>
                        @Html.ValidationMessageFor(model => model.VehicleId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>Branch</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </div>
                            @Html.DropDownList("BranchId", null, "--- Please Select ---", new { @class = "form-control", @required = "required" })
                        </div>
                        @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.Purpose)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-pencil"></i>
                            </div>
                            @Html.TextBoxFor(m => m.Purpose, new { @class = "form-control", @placeholder = "Purpose" })
                        </div>
                        @Html.ValidationMessageFor(m => m.Purpose, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>
            <div class="row text-center">
                <a class="btn btn-default" href="@Url.Action("Index","VehicleAllocations")">
                    <i class="fa fa-angle-left"></i>
                    Back
                </a>
                <input type="submit" class="btn btn-default" value="Save" />
            </div>
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeaseManager/Views/VehicleAllocations/Details.cshtml
@model LeaseManager.Models.VehicleAllocation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VehicleAllocation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Branch.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purpose)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purpose)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeaseManager/Views/VehicleAllocations/Edit.cshtml
@model LeaseManager.Models.VehicleAllocation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleAllocation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleId, "VehicleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BranchId, "BranchId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BranchId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purpose, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purpose, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purpose, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LeaseManager/Views/VehicleAllocations/Index.cshtml
@model IEnumerable<LeaseManager.Models.VehicleAllocation>

@{
    ViewBag.Title = "Vehicle Allocations";
}

<h2 class="title text-center">@ViewBag.Title</h2>
<a class="btn btn-default" href="@Url.Action("Create","VehicleAllocations")">
    <i class="fa fa-plus"></i>
    Allocate New Vehicle
</a>
<table class="table table-hover table-striped table-responsive" id="my_list">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Branch.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicle.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Purpose)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Branch.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vehicle.Make)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Purpose)
                </td>
                <td>
                    <a href="@Url.Action("Edit","VehicleAllocations", new { id = item.Id})" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs"><i class="fa fa-edit"></i></a>
                    <a href="@Url.Action("Details", "VehicleAllocations", new { id = item.Id })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                    <a href="@Url.Action("DeleteConfirmed", "VehicleAllocations", new { id = item.Id })" onclick="return confirm('Are you sure you want to delete this record?, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Delete" class="btn btn-danger btn-simple btn-xs"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $('#my_list').dataTable(
        {
            dom: 'Bfrtip',
            lengthMenu: [
                [10, 25, 50, -1],
                ['10 rows', '25 rows', '50 rows', 'Show all']
            ],
            buttons: [
                'pageLength', 'csv', 'print'
            ],
            language: { search: "" },
            select: true
        }
    );
    $(".dataTables_filter input").addClass("search-input");
    $(".dataTables_filter input").attr('placeholder', 'Search');
    $('#my_list')
        .removeClass('display')
        .addClass('table table-striped table-hover');
</script>