LeaseManager/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LeaseManager.Models
{
    public class Branch
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Branch Name")]

        public string Name { get; set; }
        public string Location { get; set; }
        [Display(Name = "Contact Number")]
        public string ContactNumber { get; set; }

        public virtual ICollection<VehicleAllocation> VehicleAllocations { get; set; }
    }
}

LeaseManager/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeaseManager.Models;

namespace LeaseManager.Controllers
{
    public class BranchesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Branches
        public ActionResult Index()
        {
            return View(db.Branches.ToList());
        }

        // GET: Branches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // GET: Branches/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Location,ContactNumber")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Branches.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        // GET: Branches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Location,ContactNumber")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            db.Branches.Remove(branch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeaseManager/Views/Branches/Create.cshtml
@model LeaseManager.Models.Branch

@{
    ViewBag.Title = "Add New Branch";
}

<h2 class="title text-center">@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <tr>
                    <th>@Html.LabelFor(model => model.Name)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </div>
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Name" })
                        </div>
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.ContactNumber)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                            </div>
                            @Html.TextBoxFor(m => m.ContactNumber, new { @class = "form-control", @placeholder = "Contact Number" })
                        </div>
                        @Html.ValidationMessageFor(m => m.ContactNumber, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.Location)</th>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            @Html.TextBoxFor(m => m.Location, new { @class = "form-control", @placeholder = "Location" })
                        </div>
                        @Html.ValidationMessageFor(m => m.Location, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>
            <div class="row text-center">
                <a class="btn btn-default" href="@Url.Action("Index","Branches")">
                    <i class="fa fa-angle-left"></i>
                    Back
                </a>
                <input type="submit" class="btn btn-default" value="Save" />
            </div>
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeaseManager/Views/Branches/Details.cshtml
@model LeaseManager.Models.Branch

@{
    ViewBag.Title = "Branch Details";
}

<h2 class="title text-center">@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-6">
        <table class="table">
            <tr>
                <th>Name</th>
                <td>
                    <div class="input-group">
                        @Html.DisplayFor(m => m.Name, new { @class = "form-control", @placeholder = "Name" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th style="width:200px">Location</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Location, new { @class = "form-control", @placeholder = "Location" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Location, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>Route</th>
                <td>
                    <div class="input-group">
                        @Html.DisplayFor(m => m.ContactNumber, new { @class = "form-control", @placeholder = "Contact Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.ContactNumber, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" href="@Url.Action("Index","Branches")">
        <i class="fa fa-angle-left"></i>
        Back to List
    </a>
</div>

LeaseManager/Views/Branches/Edit.cshtml
@model LeaseManager.Models.Branch

@{
    ViewBag.Title = "Edit";
}

<h3 align="center">Edit Branch Details</h3>
<br />
@using (Html.BeginForm(actionName: "Edit", controllerName: "Branches", routeValues: null, method: FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <div class="col-md-4">
            <table>
                <tr>
                    <th width="80px">@Html.LabelFor(model => model.Name)</th>
                    <td>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th width="80px">@Html.LabelFor(model => model.Location)</th>
                    <td>
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "Location" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th width="80px">@Html.LabelFor(model => model.ContactNumber)</th>
                    <td>
                        @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "ContactNumber" } })
                        @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn btn-default" href="@Url.Action("Index","Branches")">
                            <i class="fa fa-angle-left"></i>
                            Back to List
                        </a>
                    </td>
                    <td class="pull-right">
                        <input type="submit" value="Save Changes" class="btn btn-default" />
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

LeaseManager/Views/Branches/Index.cshtml
@model IEnumerable<LeaseManager.Models.Branch>

@{
    ViewBag.Title = "Branches";
}

<h2 class="title text-center">@ViewBag.Title</h2>
<a class="btn btn-default" href="@Url.Action("Create","Branches")">
    <i class="fa fa-plus"></i>
    Add New Branch
</a>
<table class="table table-hover table-striped table-responsive" id="my_list">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNumber)
                </td>
                <td>
                    <a href="@Url.Action("Edit","Branches", new { id = item.Id})" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs"><i class="fa fa-edit"></i></a>
                    <a href="@Url.Action("Details", "Branches", new { id = item.Id })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                    <a href="@Url.Action("DeleteConfirmed", "Branches", new { id = item.Id })" onclick="return confirm('Are you sure you want to delete this record?, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Delete" class="btn btn-danger btn-simple btn-xs"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $('#my_list').dataTable(
        {
            dom: 'Bfrtip',
            lengthMenu: [
                [10, 25, 50, -1],
                ['10 rows', '25 rows', '50 rows', 'Show all']
            ],
            buttons: [
                'pageLength', 'csv', 'print'
            ],
            language: { search: "" },
            select: true
        }
    );
    $(".dataTables_filter input").addClass("search-input");
    $(".dataTables_filter input").attr('placeholder', 'Search');
    $('#my_list')
        .removeClass('display')
        .addClass('table table-striped table-hover');
</script>